//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRD_first_web_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria
    {
        public int Id { get; set; }
        public int Usuario { get; set; }
        public byte[] foto { get; set; }
    }
}
